name: the_movie_db_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  go_router: ^3.0.7
  intl: ^0.17.0
  dio: ^4.0.6
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
  tmdb_api: ^2.1.0
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.18.0
  freezed: ^2.0.2
  json_serializable: ^6.1.6
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/no_image.png